// <auto-generated />
namespace eStore_2017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201711170531376_createorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
